name: Github-Action-test2
on: 
  push:
    branches:
      - master
      - main

jobs:
  job_id_1:
    name: job_id_1_name
    runs-on: ubuntu-latest

    steps:
      - name: job1-set-env
        env:
          MY_VAR1: 'xxoo1'
          MY_VAR2: 'ooxx2'

      - name: job1-checkout-test
        uses: actions/checkout@v3
        with:
          ref: "master"

