name: Github-Action-Demo
on: 
  push:
    branches:
      - master
      - main

  # schedule:
  #   - cron: '0 * * * *'

jobs:
  job_id_1:
    name: job_id_1_name
    runs-on: ubuntu-latest

    steps:
      - name: job1-checkout-test
        uses: actions/checkout@v3
        with:
          ref: 'master'   # branch, tag, sha to checkout

      - name: job1-shell-test
        id: job1-shell-test-id
        shell: bash
        run: |
          ls -al

      - name: job1-get-output
        shell: bash
        run: |
          echo "job1-shell-test outputs: ${{steps.job1-shell-test-id.outputs}}"

  job_id_2:
    name: job_id_2_name
    runs-on: ubuntu-latest

    steps:
      - name: job2-pwd
        shell: bash
        run: |
          pwd

      - name: job2-mkdir
        shell: bash
        run: |
          mkdir -p ~/data1/data2

      - name: job2-cd
        shell: bash
        run: |
          cd ~/data1/data2 && pwd

      - name: job2-pwd-2
        shell: bash
        run: |
          pwd

  job_id_3:
    name: job_id_3_name
    runs-on: ubuntu-latest

    steps:
      - name: job3-secret
        shell: bash
        run: |
          echo "password: ${{secret.PASS}}"
