name: Github-Action-test2
on: 
  push:
    branches:
      - master
      - main

jobs:
  job_id_1:
    name: job_id_1_name
    runs-on: ubuntu-latest

    steps:
      - name: job1-checkout-test
        uses: actions/checkout@v3
        with:
          ref: "master"
          
      - name: job1-shell-test
        id: job1-shell-test-id
        shell: bash
        run: |
          ls -al

      - name: job1-get-output
        shell: bash
        run: |
          echo "job1-shell-test outputs: ${{steps.job1-shell-test-id.outputs}}"

