name: Github-Action-Demo
on: 
  push:
    branches:
      - master
      - main

  # schedule:
  #   - cron: '0 * * * *'

env:
  env1: "Hello Shanghai"

jobs:
  # 第三方 actions
  job_id_1:
    name: job_id_1_name
    runs-on: ubuntu-latest

    steps:
      - name: job1-checkout-test
        uses: actions/checkout@v3
        with:
          ref: 'master'   # branch, tag, sha to checkout

      - name: job1-shell-test
        id: job1-shell-test-id
        shell: bash
        run: |
          ls -al

      - name: job1-get-output
        shell: bash
        run: |
          echo "job1-shell-test outputs: ${{steps.job1-shell-test-id.outputs}}"

  # shell 命令
  job_id_2:
    name: job_id_2_name
    runs-on: ubuntu-latest

    steps:
      - name: job2-pwd
        shell: bash
        run: |
          pwd

      - name: job2-mkdir
        shell: bash
        run: |
          mkdir -p ~/data1/data2

      - name: job2-cd
        shell: bash
        run: |
          cd ~/data1/data2 && pwd

      - name: job2-touch-file
        shell: bash
        run: |
          cd ~ && touch t.txt && echo 'hello' > t.txt


      - name: job2-pwd-2
        shell: bash
        run: |
          pwd

      - name: job2-ls
        shell: bash
        run: |
          cd ~ && ls -al

  # 环境变量
  job_id_3:
    name: job_id_3_name
    runs-on: ubuntu-latest
    env:
      env2: "Hello China"

    steps:
      - name: job3-secret
        shell: bash
        run: |
          echo "password: ${{secrets.PASS}}"

      - name: job3-variable
        shell: bash
        run: |
          echo "VAR_1: ${{vars.VAR_1}} VAR_2: ${{vars.VAR_2}}"

      - name: job3-env
        shell: bash
        env:
          env3: "Hello World"
        run: |
          echo "env1: $env1, env2: $env2, env3: $env3"

  # 输出捕获
  job_id_4:
    name: job_id_4_name
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT

  job_id_5:
    name: job_id_5_name
    runs-on: ubuntu-latest
    needs: job_id_4
    steps:
      - name: job1-get-output
        run: |
          echo "${{needs.job_id_4.outputs.output1}} ${{needs.job_id_4.outputs.output2}}"

  # apt
  job_id_6:
    name: job_id_6_name
    runs-on: ubuntu-latest
    steps:
      # 需要权限的命令需要加 sudo , linux && macos
      - name: job1-apt-rsync-git
        run: |
          sudo apt install -y rsync git

      - name: job2-version
        run: |
          rsync --version && git --version

      - name: job3-lsb
        run: |
          lsb_release  -a
